### ISSUE TITLE
Production ready??

### ISSUE THREAD

**Issue by robbyoconnor** [gbrlsnchs/jwt#1]
I'm unsure if this is production ready...it seems to be the most complete -- there are only two libraries that bother to validate the all the fields in a claim...

**Comment by gbrlsnchs** [comment]
I haven't released version 1.x yet because the lib still needs to be tested on Windows. I'll work on that issue this week. Also, until this point, no one reported any bugs, so I guess it's OK to release v1.

**Comment by robbyoconnor** [comment]
Very few -- all but two: yours, and https://github.com/SermoDigital/jose
actually implement the whole standard...it's weird that
https://github.com/dgrijalva/jwt-go is so popular -- it's almost as if
nobody did any research whatsoever...

**Comment by metaleap** [comment]
So, ignoring Windows here, back on the question-at-hand: *is it*?  :grin:

**Comment by gbrlsnchs** [comment]
@metaleap Ignoring Windows, I don't see why it wouldn't be production ready, but only time can really tell. The package is tested and until now, no bugs found. I've been using it myself, but only in small projects. But I can't release v1.x without having tests on Windows first.

And thanks for the tips about README, I'll update it soon.
