### ISSUE TITLE
Ecdsa Example

### ISSUE THREAD

**Issue by addy419** [gbrlsnchs/jwt#10]
I'm new to go.
and I'm having problem with NewES256(priv *priv_key,pub *public_key)
how to pass .pem file contents to the function.
Passing string from file give
```
./server.go:17:22: cannot use private_key (type string) as type *ecdsa.PrivateKey in argument to jwt.NewES256
./server.go:17:22: cannot use public_key (type string) as type *ecdsa.PublicKey in argument to jwt.NewES256
```

how should i convert it to *ecdsa.PrivateKey and *ecdsa.PublicKey respectively?

**Comment by gbrlsnchs** [comment]
Hello, you should use https://golang.org/pkg/crypto/x509/#ParseECPrivateKey to parse the contents of PEM file to an ECDSA private key, then use https://golang.org/pkg/crypto/ecdsa/#PrivateKey.Public to get a public key from the private one. Does this solve your problem? :smile:

**Comment by addy419** [comment]
Thanks Everything Works Except

`PublicKey := PrivateKey.PublicKey` gives

`cannot use PublicKey (type ecdsa.PublicKey) as type *ecdsa.PublicKey in argument to jwt.NewES256`

and

`PublicKey := PrivateKey.PublicKey` gives
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4fe35a]

goroutine 1 [running]:
main.main()
	/home/aditya/go/server.go:16 +0xba
exit status 2

```

**Comment by addy419** [comment]
Thanks😁, it worked.
I just had to use 
` block, _ := pem.Decode([]byte(pemEncoded))`
