### ISSUE TITLE
Installation link points to not existing

### ISSUE THREAD

**Issue by IceflowRE** [gbrlsnchs/jwt#13]
`vgo get -u github.com/gbrlsnchs/jwt/v2` and `go get -u github.com/gbrlsnchs/jwt/v2`

**Comment by gbrlsnchs** [comment]
What version of Go are you using?

**Comment by IceflowRE** [comment]
```
$ go get github.com/gbrlsnchs/jwt/v2
package github.com/gbrlsnchs/jwt/v2: cannot find package "github.com/gbrlsnchs/jwt/v2" in any of:
        /usr/lib/go/src/github.com/gbrlsnchs/jwt/v2 (from $GOROOT)
        /home/iceflower/go/src/github.com/gbrlsnchs/jwt/v2 (from $GOPATH)
```
version:
`go version go1.11.4 linux/amd64`

**Comment by gbrlsnchs** [comment]
@IceflowRE I installed `go1.11.4` and tested it using the same commands. It's working, so I guess it's an issue with your Go toolchain. Since the link isn't broken, I'm closing this issue.
