### ISSUE TITLE
token.Algorithm() empty?

### ISSUE THREAD

**Issue by pawmart** [gbrlsnchs/jwt#18]
For some reason I can not get hold of 'alg' from the header. Any suggestions, please?

Type and Payload data are available and properly Unmarshal-ed.

```	
        payload, sig, err := jwt.Parse(tokenString)
	if err != nil {
		return nil, errors.New("token invalid: " + err.Error())
	}

	if err = jwt.Unmarshal(payload, &token); err != nil {
		return nil, errors.New("token malformed: " + err.Error())
	}

	log.Log("Parsing token....")
	log.Log("alg is" + token.Algorithm())
	log.Log("typ is" + token.Type())
```

**Comment by gbrlsnchs** [comment]
Is the token also generated with this lib? If so, maybe you're missing [`JWT.SetAlgorithm`](https://godoc.org/github.com/gbrlsnchs/jwt#JWT.SetAlgorithm) method? If not, I might need some more information... I think I'll need at least the header (which might not have any sensitive info).

**Comment by pawmart** [comment]
Token is not generated with this library but [jwt](https://jwt.io/) website decodes it just fine, so this is defo a valid JWT token.

```eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuYXhsZE1CUElzUm92Z2J6N3J6WDJDVVQ3VzAiLCJpc3MiOiJhdm9jb3BkcyIsImV4cCI6MTU1MDIyMTYzMCwiaWF0IjoxNTUwMTM1MjMwLCJhdWQiOiJuYXhsZE1CUElzUm92Z2J6N3J6WDJDVVQ3VzAiLCJzY29wZSI6InNlcnYifQ.N-FohKedEqs-IMKDVn3CJB4LuAtQ61-MSPbx-ZV1clc```

I can get hold of any info from the token, but not 'alg' and I need to know the algoritm so i can decide how to sign it...
![screenshot 2019-02-14 at 18 38 15](https://user-images.githubusercontent.com/5460632/52809352-e7d93200-3087-11e9-8cbc-b1624826c678.png)

**Comment by pawmart** [comment]
OK pointer issue ! ;(

```
	token = new(Token)
	if err = jwt.Unmarshal(payload, token); err != nil {
		return nil, errors.New("token malformed: " + err.Error())
	}

	log.Log("Parsing token....")
	log.Log(token)
	log.Log("alg2 is" + token.JWT.Algorithm())
	log.Log("alg is" + token.Algorithm())
	log.Log("typ is" + token.Type())
	log.Log("kid is" + token.KeyID())
	log.Log("cty is" + token.ContentType())
```

works just fine!

**Comment by gbrlsnchs** [comment]
I see. As a best practice, I like to declare the receiver token as following:
```go
var token Token
if err := jwt.Unmarshal(payload, &token); err != nil {
	// ...
}
```

Anyway, I'm glad you solved your issue. Have fun! :smile:
