### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by YanMyoKyaw** [gbrlsnchs/jwt#22]
When I did go get github.com/gbrlsnchs/jwt
It shown pub.size undefined(type *rsa.PublicKey has no field or method Size)

Pls show me how to solve it.

**Comment by gbrlsnchs** [comment]
This is because it's only compatible with `go1.11`. You can still use `v2`, which is compatible with `go1.10`.

**Comment by YanMyoKyaw** [comment]
thank bro, thank a lot
