### ISSUE TITLE
Is it possible to select a verifier after learning about the token's algorithm ("alg") or key ID ("kid")?

### ISSUE THREAD

**Issue by seh** [gbrlsnchs/jwt#23]
In [the _github.com/dgrijalva/jwt-go_ package](https://github.com/dgrijalva/jwt-go), there are two token consuming functions—[`Parse`](https://godoc.org/github.com/dgrijalva/jwt-go#Parse) and [`ParseWithClaims`](https://godoc.org/github.com/dgrijalva/jwt-go#ParseWithClaims)—that accept a callback of type [`Keyfunc`](https://godoc.org/github.com/dgrijalva/jwt-go#Keyfunc), allowing the caller to first see a token's "alg" and "kid" header values in order to select which key to use for verifying the token. Is it possible to do something similar with this package?

I see that as of version 3, one can call [`jwt.Verify`](https://godoc.org/github.com/gbrlsnchs/jwt#Verify) to get a [`jwt.RawToken`](https://godoc.org/github.com/gbrlsnchs/jwt#RawToken) back, but that requires that **the caller know a priori which verifier to use**. This interface works well enough for consumers that accept only a single signing method (algorithm and hash), but it isn't sufficient for consumers that want to react to the declarations in the token's header to choose from several available verification options.

Of course, it's possible to keep calling `jwt.Verify` with different `Verifier`s, but that wastes work finding the three components of the token each time. Am I missing another approach?

**Comment by seh** [comment]
A potential extension of the current interface is something like this:
```go
func VerifyPerHeader(token []byte, choose func(*Header) Verifier) (r RawToken, err error)
```
The question is whether the `choose` function can fail. As shown there, it doesn't allow returning an error, but it could. Alternately, you could say that if `choose` returns nil, that means it can't find a suitable `Verifier`, and `VerifyPerHeader` should return a distinguished error that the caller could detect if necessary: `return nil, ErrNoVerifier`.

Alternately, you could define the `choose` function signature as `func(*Header) (Verifier, error)` and , if the the returned `error` is non-nil, return that from `VerifyPerHeader`. That still leaves the possibility, though, that `choose` could return a nil `Verifier`, against which you'd have to defend anyway.

**Comment by gbrlsnchs** [comment]
I see. You have a very important point. `v3` is still in alpha, so, yeah, the API will definitely change and your feedback is very important. Maybe parsing before verifying should be the way to go. `v2` deals with this issue nicely but it's too complex, I want `v3` to be simpler.

**Comment by gbrlsnchs** [comment]
This is now possible via [`RawToken.Decode`](https://godoc.org/github.com/gbrlsnchs/jwt#RawToken.Decode). One is able to decode the token independently of verification.

**Comment by seh** [comment]
Nice. Thank you, Gabriel.
I'll give this a try over the next few days.

Reading the code, it looks like the proper flow is as follows:
- Call `Parse` to get a `RawToken`.
- Call `RawToken.Decode` to get the claims and the header.  
  At this point, the claims are still suspect, as they haven't been verified.
  Inspect the header to get a key ID, and choose a `Verifier`.
- Call `RawToken.Verify` using the chosen `Verifier`.  
  If that succeeds, proceed to use the claims.

Is that correct?

**Comment by gbrlsnchs** [comment]
Yes, that's the exact flow. Thanks for your input, it helped to improve `v3` a lot.

**Comment by seh** [comment]
Yesterday I finally upgraded to version [the _alpha.4_ release](https://github.com/gbrlsnchs/jwt/releases/tag/v3.0.0-alpha.4). It required only a few small changes to my code, and most of those changes were removing a couple of adapter types I had written to deal with the `jwt.JWT` type and the `HeaderAddr` method. It's much simpler now. Thanks again!

**Comment by gbrlsnchs** [comment]
@seh I'm glad to read that. Thank you for the feedback. I'll try not to break the API again until `v3.0`, still I can't promise anything. Have a good one!
