### ISSUE TITLE
“go get -u github.com/gbrlsnchs/jwt/v3” Error occurred

### ISSUE THREAD

**Issue by aimo-x** [gbrlsnchs/jwt#29]
```
go get -u github.com/gbrlsnchs/jwt/v3
package github.com/gbrlsnchs/jwt/v3: cannot find package "github.com/gbrlsnchs/jwt/v3" in any of:
        C:\Go\src\github.com\gbrlsnchs\jwt\v3 (from $GOROOT)
        C:\Users\mukon\Desktop\go\src\github.com\gbrlsnchs\jwt\v3 (from $GOPATH)
```

**Comment by gbrlsnchs** [comment]
Hello. Everybody's been a novice at some point in their lives, don't worry, glad you asked. First be sure you're running go1.11 or greater and then please try the following:
1. Go to the directory of your project
2. Run `GO111MODULE=on go get -u github.com/gbrlsnchs/jwt`
3. Check if there's success now

There is that goddamn environment variable for go1.11 (I think in go1.12 it is set `on` by default) so I might end up updating the README as you're not the first one that runs into trouble trying to use it with modules.

**Comment by aimo-x** [comment]
First of all, thank you very much. According to your prompt, the problem has been solved!

**Comment by gbrlsnchs** [comment]
Good to know. I just edited my comment, be sure to `go get` the right version (`v3`).
