### ISSUE TITLE
What the difference from that?

### ISSUE THREAD

**Issue by chaseSpace** [gbrlsnchs/jwt#33]
one.
```
hd, err := jwt.Verify(token, hs, &pl)
```
two.
```
hd, err = jwt.Verify(token, hs, &pl, ValidatePayload)
```
I created `expValidator` and `nbfValidator`,  The **hd** are the same. 
So, What is the verification? I mean the process. It won't panic even time's expired or nbf-time is expired, Work of the lib is just parse claims?
That is my problem.

**Comment by gbrlsnchs** [comment]
Hi, @chaseSpace! Could you provide a full example? I think I'll be able to help you better that way.

> What is the verification?

If you don't pass any options, `jwt.Verify` only verifies the JWT's signature. Now, if you pass `jwt.ValidatePayload` to it, it will run every `jwt.Validator` you set in it, but only after verifying the signature.

> It won't panic even time's expired or nbf-time is expired

The function doesn't panic, it returns an error. By default, only for signature verification, but by passing options to the function, you can validate claims. In your example, if valid, and the token is expired, `jwt.ErrExpValidation` is returned (considering that the token has a valid signature).

> Work of the lib is just parse claims?

Not just parse, but also signing, verifying and validating. The README file has all those examples.
