### ISSUE TITLE
Documentation seems to be outdated or modules not working as expected

### ISSUE THREAD

**Issue by LiamDotPro** [gbrlsnchs/jwt#37]
I'm currently trying to use this package again after not using it for a while and my previously working code no longer functions as intended, furthermore I don't seem to be able to use `"github.com/gbrlsnchs/jwt/v3"` anymore either. Adopting this module at this point in time for me is rather troublesome, I have also sent a few messages in gitter but that seems disused.

**Comment by gbrlsnchs** [comment]
Hello there. The Gitter chat is active, however it hasn't been used much, that's why I'm not 24/7 there.

Anyway, what version of Go are you using? And what version of this library are you using? What errors are you facing? Please, I need more details to be able to help.
