### ISSUE TITLE
Issue with verificiation of JWT tokens

### ISSUE THREAD

**Issue by RealLinkers** [gbrlsnchs/jwt#40]
**Describe the bug**
Verification isn't working for the examples with HMAC. If i go onto JWT.IO and manually paste the JWT and enter the secret, everything works as expected.

**To Reproduce**
1. Combine the 2 examples of sign and verify
2. Run the program

**Expected behavior**
Verification isn't happening as expected

**Please complete the following information:**
 - OS: Linux
 - Go version 1.13.3
 - This package's version latest

**Additional context**

**Comment by gbrlsnchs** [comment]
Hello! 😺 

Sorry, [I could not reproduce your issue](https://play.golang.org/p/bNxO7iU1pY7). If your issue isn't exactly what I have exemplified in the playground, would you mind providing another example in the same way I did (by sharing the Go Playground URL)?

Thanks!
