### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by MarlikAlmighty** [gbrlsnchs/jwt#41]
I have a private key and token signed by alg rs256, could you describe how to work with your library? You have no examples.

**Comment by gbrlsnchs** [comment]
I'll reopen this because I think it's important to have more examples in README. I'll soon add them. 😸

**Comment by MarlikAlmighty** [comment]
Thanks.

**Comment by MarlikAlmighty** [comment]
Something like this.

![Снимок экрана от 2019-12-03 08-45-53](https://user-images.githubusercontent.com/17222940/70687943-a1615d80-1cc1-11ea-8b3b-21c0e90c04f0.png)
