### ISSUE TITLE
Getting the header from a token

### ISSUE THREAD

**Issue by pf512** [gbrlsnchs/jwt#42]
An early 3.0 beta allowed me to parse a token to get the header.  I would use this to get the kid to look up the public key for verifying.

Now it seems I have to specify what kind of token it is (RS256, ES512, etc) before getting the header.  Is this correct?

One of my favorite tools is the jwt.io site.  I can paste in a token to get the header and payload.  Shouldn't I be able to get the same data from the jwt package without going through a verify function?

**Comment by seh** [comment]
You can use [`jwtutil.Resolver`](https://godoc.org/github.com/gbrlsnchs/jwt/jwtutil#Resolver) for this purpose. Pass a `Resolver` value to [the `jwt.Verify` function](https://godoc.org/github.com/gbrlsnchs/jwt#Verify) as the second "alg" parameter, as `Resolver` satisfies [the `Algorithm` interface](https://godoc.org/github.com/gbrlsnchs/jwt#Algorithm). This assumes that the reason you want the "kid" field value is to look up a key with which to verify the token's signature.

There was some previous discussion in #23 and, more recently for the current interface in https://github.com/gbrlsnchs/jwt/pull/30#issuecomment-509786101. It's an odd design, difficult to discover on your own, but I can confirm that it does work if your goal is to look up a key by its ID.

**Comment by pf512** [comment]
Thank you!  Solved my issue.  

We also store custom data in our payload that we use prior to verification.  The previous 3.0 beta we used allowed us to get the payload.  Is there a way to still get the payload without verifying the token?

**Comment by gbrlsnchs** [comment]
Sorry, all this oddity is due to the design decision of not allowing to decode the JWT without also verifying it. It might be possible to export the functions that parse header and payload, though.

**Comment by gbrlsnchs** [comment]
I decided not to allow checking the payload without verifying the whole token. The intention is to make a safer API, although boring. You can always Base64 decode the raw incoming token to get whatever information you need, at your own risk. I advise against trusting information of unverified tokens.
