### ISSUE TITLE
Can I use map[string]interface{} in place of the CustomPayload?

### ISSUE THREAD

**Issue by elgs** [gbrlsnchs/jwt#44]
I wonder if I can use map[string]interface{} in place of the CustomPayload? I think that way it will be a lot easier to use the api.

**Comment by gbrlsnchs** [comment]
Hi, @elgs! Yes, you can use whatever you want, as it accepts an `interface{}` as payload.

Here is an example: https://play.golang.org/p/fAu2drqn7nR.

I'm closing this but feel free to reopen if you feel the need to.

**Comment by elgs** [comment]
Thank you! That's awesome!
