### ISSUE TITLE
Why not release V3.0 ？

### ISSUE THREAD

**Issue by liushuiyuan001** [gbrlsnchs/jwt#45]
Just curious...Why not ?

**Comment by gbrlsnchs** [comment]
I intended to refactor integration tests a little, but I had no time to do so. The API is stable though, and no critical issues arose for some time. I'll try to release `v3` very soon, thanks for reminding me!

**Comment by gbrlsnchs** [comment]
`v3` has been released. No major issues were risen during RC releases, so I just tagged the latest release.
