### ISSUE TITLE
关于token refresh问题 

### ISSUE THREAD

**Issue by xhochipe** [gbrlsnchs/jwt#5]
您好，这个包里面实现了token自动刷新续期的功能了吗，我看了下源码好像没有这个功能

**Comment by gbrlsnchs** [comment]
Hi @xhochipe, I'm sorry for taking some time to answer you.

I don't speak Chinese, so I'm sorry but I had to translate your text using Google Translator. You seem to be asking about automatic refresh/renewal, which I don't quite understand. Could you please elaborate your issue with some more details and real usage examples? I'm eager to help you as soon as I understand your issue a little better. Thanks!

**Comment by piLinux** [comment]
Most probably he was looking for this:
https://auth0.com/blog/refresh-tokens-what-are-they-and-when-to-use-them/

Actually I also am searching for a solution.

Thank you :)
