### ISSUE TITLE
jwt.ValidateHeader possible bug with ed25519 / EdDSA headers

### ISSUE THREAD

**Issue by rorycl** [gbrlsnchs/jwt#50]
Hi @gbrlsnchs 

I've been testing ed25519 signing of jwts, which I have been generating with python's jwt module. The jwt I'm using is [here](https://jwt.io/#debugger-io?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJFZERTQSIsImtpZCI6InI2NDcifQ.eyJpYXQiOjE2MjI5MjkwMzksIm5iZiI6MTYyMjkyNTQzOSwiZXhwIjoxNjIyOTQ3MDM5LCJpc3MiOiJ0ZXN0IiwiYXVkIjoiaGVscC50ZXN0LmNvbSIsImNvbnRlbnQiOnsic29tZSI6ImNvbnRlbnQifX0.GgNleA6RzI2PT0NRNtKDw9vBifpfp9nuj40jLgL31CN_Wzqb-Mlm3M4NOK5YMoRwNd_4eZSxgYkF6cVDX3g1CQ).

My comments are in relation to [RFC8037/A.5](https://datatracker.ietf.org/doc/html/rfc8037#appendix-A.5).

Excuse me if I'm making a stupid error.

**Describe the bug**

A jwt constructed with a ed25519 keypair errors in `ValidateHeader` with `"EdDSA": invalid "alg" field`

**To Reproduce**

```
    hd, err := jwt.Verify(token, k, &pl, validatePayload, jwt.ValidateHeader)
    if err != nil {
        fmt.Println(err)
    }
```
See https://gist.github.com/b8a093bdd3f2a4ccb7e12831b37a5154 for a full example

It appears that `ValidateHeader` in verify.go is depending on `_ Algorithm = new(Ed25519)` in ed25519.go. I believe that name is incorrect for an ed25519 signed jwt:

```
// ValidateHeader checks whether the algorithm contained
// in the JOSE header is the same used by the algorithm.
func ValidateHeader(rt *RawToken) error {
    if rt.alg.Name() != rt.hd.Algorithm {
        return internal.Errorf("jwt: %q: %w", rt.hd.Algorithm, ErrAlgValidation)
    }
    return nil
} 
```

**Expected behavior**

That the `"alg": "EdDSA"` be accepted for ed25519 signed jwts.

Perhaps It would also be good for the user to explicitly state the accepted algorithms, as suggested by [jwt.io's advice to check signatures](https://auth0.com/docs/tokens/json-web-tokens/validate-json-web-tokens#check-signature). The explicit argument of `algorithms=["RS256"]` for example, given in [pyjwt](https://pyjwt.readthedocs.io/en/latest/usage.html#encoding-decoding-tokens-with-rs256-rsa), might be worth considering.

**Please complete the following information:**
 - OS: Debian Linux
 - Go version 1.15.9 linux/amd64
 - This package's version github.com/gbrlsnchs/jwt/v3 v3.0.0

**Comment by gbrlsnchs** [comment]
Thanks for bringing this up and sorry for the late response. You are correct, and I've followed other libs also updating this same mistake. Fixed in `v3.0.1`, please update!
