### ISSUE TITLE
Verifying Audience according to the spec

### ISSUE THREAD

**Issue by benjaminjb** [gbrlsnchs/jwt#6]
Right now, the Audience value is defined as a string in the JWT struct:
https://github.com/gbrlsnchs/jwt/blob/master/jwt.go#L17

And the Audience validator checks string == string:
https://github.com/gbrlsnchs/jwt/blob/master/validators.go#L29-L37

But the JWT spec for audience claims says that aud can be a string or a list of strings:
https://tools.ietf.org/html/rfc7519#section-4.1.3

This is how auth0/node-jsonwebtoken deals with aud too: 
> The audience can be checked against a string, a regular expression or a list of strings and/or regular expressions. Eg: "urn:foo", /urn:f[o]{2}/, [/urn:f[o]{2}/, "urn:bar"]

https://github.com/auth0/node-jsonwebtoken/tree/master

Would you be open to a PR that dealt with aud to cover the case where it's a list of strings and not just a string?

Or is there some reason why you won't want to make that change?

**Comment by gbrlsnchs** [comment]
I agree, I think it should definitely match a value against an array of strings instead of how it's being done. The validator should be a variadic function. A PR is very welcome.

**Comment by benjaminjb** [comment]
If there's any problems or comments, I'm all ears.

**Comment by gbrlsnchs** [comment]
@benjaminjb This will be a feature in `v3`. I intend to release it after `go1.12` is released, as `v3` will not be compatible with `go1.10` anymore, so I want to have at least two release versions compatible.
